name: MkDocs documentation
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mkdocs
      - name: Build documentation
        run: python docs/autogen.py
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy -f docs/mkdocs.yml -c -v --force